version: "3.8"

services:
  go:
    volumes:
      - ./app/:/app/
    working_dir: /app
    tty: true
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - 2345:2345
    container_name: qiita_go
